const JOB_DATA = [
    {
        id: 1,
        title: "SDE Intern",
        company: "Flipkart",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Data Structures", "Problem Solving"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹40k–₹60k/month Internship",
        applyUrl: "https://www.flipkart.com/careers",
        description: "Join Flipkart's engineering team as an intern. You will work on scalable systems and contribute to the core e-commerce platform. Ideal for students with strong fundamental coding skills."
    },
    {
        id: 2,
        title: "Graduate Engineer Trainee",
        company: "TCS",
        location: "Pune",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["C++", "Java", "SQL"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "3–4.5 LPA",
        applyUrl: "https://www.tcs.com/careers",
        description: "Start your career with TCS. As a GET, you will undergo rigorous training and work on global projects across various domains including finance and retail."
    },
    {
        id: 3,
        title: "Junior Backend Developer",
        company: "Razorpay",
        location: "Bengaluru",
        mode: "Remote",
        experience: "0-1",
        skills: ["Node.js", "Express", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "12–18 LPA",
        applyUrl: "https://razorpay.com/jobs",
        description: "Razorpay is looking for a backend enthusiast. You'll help build the next generation of payment infrastructure in India. Experience with microservices is a plus."
    },
    {
        id: 4,
        title: "Frontend Intern",
        company: "Swiggy",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["React", "JavaScript", "Tailwind CSS"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "₹25k–₹35k/month Internship",
        applyUrl: "https://www.swiggy.com/careers",
        description: "Help Swiggy improve the food delivery experience. You'll work on consumer-facing web apps using modern frontend technologies."
    },
    {
        id: 5,
        title: "Python Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Django", "REST API"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "6–10 LPA",
        applyUrl: "https://www.zoho.com/careers",
        description: "Join Zoho's product engineering team. You will be responsible for building robust backend services for our ecosystem of business applications."
    },
    {
        id: 6,
        title: "QA Intern",
        company: "Juspay",
        location: "Bengaluru",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Selenium", "Manual Testing", "Java"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "₹20k–₹30k/month Internship",
        applyUrl: "https://juspay.in/careers",
        description: "Ensure the reliability of India's payment rails. You will perform automated and manual testing for high-traffic payment gateways."
    },
    {
        id: 7,
        title: "React Developer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "Redux", "TypeScript"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–18 LPA",
        applyUrl: "https://www.freshworks.com/careers",
        description: "Work on the award-winning Freshdesk platform. We need frontend experts who care about UX and writing clean, maintainable TypeScript code."
    },
    {
        id: 8,
        title: "Java Developer",
        company: "Infosys",
        location: "Mysuru",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "Microservices"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "4–6 LPA",
        applyUrl: "https://www.infosys.com/careers",
        description: "Infosys is hiring for its core digital transformation projects. You'll be working on enterprise Java applications for global clients."
    },
    {
        id: 9,
        title: "Data Analyst Intern",
        company: "CRED",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["SQL", "Python", "Tableau"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹30k–₹50k/month Internship",
        applyUrl: "https://www.cred.club/careers",
        description: "Analyze financial data at CRED. You'll help uncover insights that drive product decisions and marketing strategies for high-trust members."
    },
    {
        id: 10,
        title: "Software Engineer",
        company: "Capgemini",
        location: "Hyderabad",
        mode: "Remote",
        experience: "1-3",
        skills: [".NET", "Azure", "C#"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "8–12 LPA",
        applyUrl: "https://www.capgemini.com/careers",
        description: "Join our cloud transformation unit. You'll build and port enterprise applications to Azure for our European clients."
    },
    {
        id: 11,
        title: "SDE 1",
        company: "PhonePe",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Go", "Distributed Systems", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15–25 LPA",
        applyUrl: "https://www.phonepe.com/careers",
        description: "PhonePe is at the forefront of UPI payments. We are looking for engineers who can write high-performance Go code for scale."
    },
    {
        id: 12,
        title: "Full Stack Intern",
        company: "Jio",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Mean Stack", "Express", "Node.js"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "₹15k–₹25k/month Internship",
        applyUrl: "https://careers.jio.com",
        description: "Work on Bharat's digital revolution. Jio is hiring interns for its platform services team to help build everyday apps for millions."
    },
    {
        id: 13,
        title: "Backend Developer",
        company: "Zomato",
        location: "Gurugram",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "Golang", "Kafka"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "14–22 LPA",
        applyUrl: "https://www.zomato.com/careers",
        description: "Zomato's logistics engine needs you. Scale our delivery services and handle millions of orders a day with low latency."
    },
    {
        id: 14,
        title: "Android Developer",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Kotlin", "Android SDK", "MVVM"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "10–18 LPA",
        applyUrl: "https://www.paytm.com/careers",
        description: "Build the future of mobile commerce. Work on the core Paytm app and ensure a smooth experience for millions of users."
    },
    {
        id: 15,
        title: "DevOps Intern",
        company: "HCLTech",
        location: "Noida",
        mode: "Remote",
        experience: "Fresher",
        skills: ["AWS", "Docker", "Linux"],
        source: "Indeed",
        postedDaysAgo: 10,
        salaryRange: "₹18k–₹30k/month Internship",
        applyUrl: "https://www.hcltech.com/careers",
        description: "Learn cloud infrastructure orchestration at scale. Assist in managing CI/CD pipelines and cloud deployments."
    },
    {
        id: 16,
        title: "Frontend Developer",
        company: "Byju's",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "CSS3", "Next.js"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "9–15 LPA",
        applyUrl: "https://byjus.com/careers",
        description: "Create engaging learning experiences for students around the world. We need frontend devs who love building pixel-perfect UIs."
    },
    {
        id: 17,
        title: "Associate Consultant",
        company: "Wipro",
        location: "Kochi",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Salesforce", "Apex", "CRM"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "6–9 LPA",
        applyUrl: "https://www.wipro.com/careers",
        description: "Implement Salesforce solutions for enterprise clients. You will be part of our global CRM excellence team."
    },
    {
        id: 18,
        title: "Apprentice Engineer",
        company: "Amazon",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Linux", "Data Structures"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹60k–₹80k/month Internship",
        applyUrl: "https://www.amazon.jobs",
        description: "Join the AWS team in India. Work on cloud infrastructure components and learn from world-class engineers."
    },
    {
        id: 19,
        title: "SDE-1",
        company: "Ola Electric",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "1-3",
        skills: ["C++", "Embedded Systems", "RTOS"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "12–20 LPA",
        applyUrl: "https://olaelectric.com/careers",
        description: "Build the software that powers India's electric vehicles. We're looking for low-level systems engineers to join our EV revolution."
    },
    {
        id: 20,
        title: "Business Analyst",
        company: "Cognizant",
        location: "Kolkata",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Agile", "SQL", "Jira"],
        source: "Naukri",
        postedDaysAgo: 9,
        salaryRange: "7–11 LPA",
        applyUrl: "https://www.cognizant.com/careers",
        description: "Bridge the gap between business and tech. Work on requirement gathering and documentation for large-scale IT projects."
    },
    {
        id: 21,
        title: "Java Developer",
        company: "IBM",
        location: "Hyderabad",
        mode: "Remote",
        experience: "3-5",
        skills: ["Spring", "Kubernetes", "Junit"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "12–20 LPA",
        applyUrl: "https://www.ibm.com/careers",
        description: "Join IBM's Hybrid Cloud team. You'll develop cloud-native Java applications using Spring Boot and deploy on OpenShift."
    },
    {
        id: 22,
        title: "Data Scientist",
        company: "Dell Technologies",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Python", "PyTorch", "NLP"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "18–30 LPA",
        applyUrl: "https://jobs.dell.com",
        description: "Apply machine learning to solve supply chain and product telemetry problems at Dell. Experience with deep learning is highly desired."
    },
    {
        id: 23,
        title: "Technical Architect",
        company: "Accenture",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Cloud Arch", "Node.js", "Serverless"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "25–40 LPA",
        applyUrl: "https://www.accenture.com/careers",
        description: "Design and deliver cloud architectures for Fortune 500 clients. Lead engineering teams through complex digital transformations."
    },
    {
        id: 24,
        title: "Product Manager 1",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Product Sense", "Analytics", "Wireframing"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "15–25 LPA",
        applyUrl: "https://paytm.com/careers",
        description: "Own a feature vertical within the Paytm app. Drive product growth through data-driven experiments and deep user empathy."
    },
    {
        id: 25,
        title: "UI/UX Designer",
        company: "Urban Company",
        location: "Gurugram",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Figma", "User Research", "Interaction Design"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "12–22 LPA",
        applyUrl: "https://www.urbancompany.com/careers",
        description: "Reimagine home services through design. Join our design team to create simple, effective interfaces for both consumers and service partners."
    },
    {
        id: 26,
        title: "Database Admin",
        company: "Oracle",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Oracle DB", "Performance Tuning", "PL/SQL"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "15–25 LPA",
        applyUrl: "https://www.oracle.com/careers",
        description: "Join the core Oracle Database team. You'll be responsible for maintaining mission-critical databases for our global clients."
    },
    {
        id: 27,
        title: "Full Stack Developer",
        company: "Zepto",
        location: "Mumbai",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Node.js", "React", "PostgreSQL"],
        source: "Indeed",
        postedDaysAgo: 0,
        salaryRange: "20–35 LPA",
        applyUrl: "https://www.zeptonow.com/careers",
        description: "Build the engine behind 10-minute deliveries. We need full stack wizards who can move fast and build scalable systems for order management."
    },
    {
        id: 28,
        title: "SRE Associate",
        company: "Adobe",
        location: "Noida",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "Terraform", "Prometheus"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "18–28 LPA",
        applyUrl: "https://www.adobe.com/careers",
        description: "Keep the Creative Cloud running smoothly. Work on reliability engineering and automation to support millions of creative professionals."
    },
    {
        id: 29,
        title: "Cybersecurity Analyst",
        company: "Wipro",
        location: "Bengaluru",
        mode: "Remote",
        experience: "1-3",
        skills: ["Pen Testing", "SIEM", "Network Security"],
        source: "Naukri",
        postedDaysAgo: 8,
        salaryRange: "8–14 LPA",
        applyUrl: "https://www.wipro.com/careers",
        description: "Defend against modern cyber threats. Join our SOC team to monitor and respond to security incidents for our global enterprise clients."
    },
    {
        id: 30,
        title: "Mobile App Intern",
        company: "Groww",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Flutter", "Dart", "Firebase"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹25k–₹45k/month Internship",
        applyUrl: "https://groww.in/careers",
        description: "Help build the most intuitive investment app in India. Work with our mobile team on new Flutter-based features."
    },
    {
        id: 31,
        title: "Systems Engineer",
        company: "AMD",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Verilog", "Python", "ASIC Design"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "12–22 LPA",
        applyUrl: "https://www.amd.com/careers",
        description: "Join the chip design team at AMD. You'll be working on next-generations CPU/GPU verification and hardware-software co-design."
    },
    {
        id: 32,
        title: "Backend Engine",
        company: "Postman",
        location: "Bengaluru",
        mode: "Remote",
        experience: "3-5",
        skills: ["Node.js", "Redis", "Elasticsearch"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "25–45 LPA",
        applyUrl: "https://www.postman.com/careers",
        description: "Work on the API platform used by 25 million developers. Build and scale real-time collaboration features for the Postman ecosystem."
    },
    {
        id: 33,
        title: "iOS Engineer",
        company: "CRED",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Swift", "SwiftUI", "Combine"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "15–30 LPA",
        applyUrl: "https://www.cred.club/careers",
        description: "Craft premium iOS experiences for high-net-worth users. We care deeply about animations, design, and performance."
    },
    {
        id: 34,
        title: "Security Engineer",
        company: "Juspay",
        location: "Bengaluru",
        mode: "Remote",
        experience: "3-5",
        skills: ["Cryptography", "Haskell", "Rust"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "20–35 LPA",
        applyUrl: "https://juspay.in/careers",
        description: "Work on functional programming based security services. You'll ensure the mathematical correctness and safety of our payment systems."
    },
    {
        id: 35,
        title: "Frontend Intern",
        company: "Unacademy",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["React", "JS", "Material UI"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "₹20k–₹35k/month Internship",
        applyUrl: "https://unacademy.com/careers",
        description: "Build features for India's largest learning platform. Work closely with product managers and designers to deliver student value."
    },
    {
        id: 36,
        title: "Cloud Consultant",
        company: "PwC India",
        location: "Ahmedabad",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["GCP", "Kubernetes", "Shell Scripting"],
        source: "LinkedIn",
        postedDaysAgo: 9,
        salaryRange: "9–15 LPA",
        applyUrl: "https://www.pwc.in/careers",
        description: "Advise clients on their cloud journey. Help businesses migrate to GCP and modernize their legacy infrastructure."
    },
    {
        id: 37,
        title: "ML Ops Engineer",
        company: "Fractal Analytics",
        location: "Mumbai",
        mode: "Remote",
        experience: "3-5",
        skills: ["MLflow", "Kubeflow", "Docker"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15–28 LPA",
        applyUrl: "https://fractal.ai/careers",
        description: "Bridge the gap between data science and production. Build pipelines for model training, deployment, and monitoring at scale."
    },
    {
        id: 38,
        title: "Technical Writing Intern",
        company: "Newton School",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Coding", "Technical Writing", "Docs"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹15k–₹25k/month Internship",
        applyUrl: "https://www.newtonschool.co/careers",
        description: "Create educational content for aspiring software developers. You should have a knack for explaining complex tech concepts simply."
    },
    {
        id: 39,
        title: "Firmware Engineer",
        company: "Intel",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "1-3",
        skills: ["C", "Assembly", "Kernel"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "14–24 LPA",
        applyUrl: "https://www.intel.com/careers",
        description: "Write the code that stays closest to the metal. Develop bootloaders and drivers for next-generation Intel computing platforms."
    },
    {
        id: 40,
        title: "Product Analyst",
        company: "Spinny",
        location: "Gurugram",
        mode: "Onsite",
        experience: "1-3",
        skills: ["SQL", "Excel", "Data Viz"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "8–12 LPA",
        applyUrl: "https://www.spinny.com/careers",
        description: "Analyze user behavior and transaction trends for India's used car market. Help optimize the Spinny customer journey."
    },
    {
        id: 41,
        title: "PHP Developer",
        company: "Naukri.com",
        location: "Noida",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["PHP", "Laravel", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "10–16 LPA",
        applyUrl: "https://www.infoedge.in/careers",
        description: "Work on the backend of one of India's largest job portals. Maintain and optimize high-traffic PHP services."
    },
    {
        id: 42,
        title: "Golang Developer",
        company: "Gojek",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Go", "RabbitMQ", "Postgres"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "18–35 LPA",
        applyUrl: "https://www.gojek.io/careers",
        description: "Scale Gojek's transport and logistics systems. We need engineers who are obsessed with clean code and distributed systems."
    },
    {
        id: 43,
        title: "DevOps Engineer",
        company: "Atlassian",
        location: "Bengaluru",
        mode: "Remote",
        experience: "3-5",
        skills: ["Python", "K8s", "CircleCI"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "25–45 LPA",
        applyUrl: "https://www.atlassian.com/careers",
        description: "Help build the future of team collaboration. Join our infra team to manage the systems that power Jira and Confluence."
    },
    {
        id: 44,
        title: "Blockchain Intern",
        company: "Polygon",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Solidity", "Ether.js", "Ethereum"],
        source: "LinkedIn",
        postedDaysAgo: 5,
        salaryRange: "₹30k–₹60k/month Internship",
        applyUrl: "https://polygon.technology/careers",
        description: "Learn and build on the world's most adopted L2. Work with the core engineering team on smart contract protocols."
    },
    {
        id: 45,
        title: "React Native Dev",
        company: "Meesho",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React Native", "JS", "Android/iOS"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "12–20 LPA",
        applyUrl: "https://www.meesho.io/careers",
        description: "Empower millions of entrepreneurs in Bharat. Join our mobile team to build high-performance mobile commerce experiences."
    },
    {
        id: 46,
        title: "Support Engineer",
        company: "Microsoft",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Networking", "Troubleshooting", "Azure"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "6–10 LPA",
        applyUrl: "https://careers.microsoft.com",
        description: "Provide technical support for enterprise customers on Azure. Help troubleshoot complex cloud infrastructure and networking issues."
    },
    {
        id: 47,
        title: "QA Engineer",
        company: "Lenskart",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Appium", "REST Assured", "API Testing"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "9–14 LPA",
        applyUrl: "https://lenskart.com/careers",
        description: "Ensure the reliability of Lenskart's omnichannel platform. Build robust automated test suites for our mobile and web apps."
    },
    {
        id: 48,
        title: "Ruby on Rails Dev",
        company: "AirBnB",
        location: "Gurugram",
        mode: "Hybrid",
        experience: "3-5",
        skills: ["Ruby", "Rails", "GraphQL"],
        source: "LinkedIn",
        postedDaysAgo: 7,
        salaryRange: "30–50 LPA",
        applyUrl: "https://www.airbnb.com/careers",
        description: "Work with the global Airbnb engineering team from India. Scale the core reservation systems using Ruby on Rails."
    },
    {
        id: 49,
        title: "Embedded Intern",
        company: "Samsung R&D",
        location: "Noida",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C", "Microcontrollers", "IoT"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://www.samsung.com/careers",
        description: "Research and develop next-gen consumer electronics. You'll be working on embedded software for smart home devices."
    },
    {
        id: 50,
        title: "SDE 2",
        company: "Blinkit",
        location: "Gurugram",
        mode: "Onsite",
        experience: "3-5",
        skills: ["Java", "Kafka", "DynamoDB"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "25–40 LPA",
        applyUrl: "https://blinkit.com/careers",
        description: "Scale quick commerce in India. Work on the warehouse and inventory management systems to ensure 10-minute grocery delivery."
    },
    {
        id: 51,
        title: "SDE 1",
        company: "Oracle",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Java", "Spring Boot", "Docker"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "12–20 LPA",
        applyUrl: "https://www.oracle.com/careers",
        description: "Join the OCI engineering team. You'll build and maintain foundational cloud services for enterprise customers."
    },
    {
        id: 52,
        title: "Node.js Developer",
        company: "Deel",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        skills: ["Node.js", "Serverless", "Postgres"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "15–30 LPA",
        applyUrl: "https://www.deel.com/careers",
        description: "Work at one of the world's fastest-growing startups. Build features for Deel's global payroll and compliance platform."
    },
    {
        id: 53,
        title: "Machine Learning Intern",
        company: "Nvidia",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C++", "CUDA", "PyTorch"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹50k–₹75k/month Internship",
        applyUrl: "https://www.nvidia.com/careers",
        description: "Contribute to the future of AI. Work on high-performance libraries for deep learning on Nvidia GPUs."
    },
    {
        id: 54,
        title: "Python SDE",
        company: "Thoughtworks",
        location: "Pune",
        mode: "Remote",
        experience: "1-3",
        skills: ["Python", "FastAPI", "TDD"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "10–16 LPA",
        applyUrl: "https://www.thoughtworks.com/careers",
        description: "Join our community of technologists. We practice extreme programming, TDD, and clean code for high-impact projects."
    },
    {
        id: 55,
        title: "Android Intern",
        company: "PharmEasy",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Android", "Java", "Retrofit"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹18k–₹30k/month Internship",
        applyUrl: "https://pharmeasy.in/careers",
        description: "Make healthcare accessible in India. Work with the mobile team to improve user accessibility and healthcare features."
    },
    {
        id: 56,
        title: "Lead Developer",
        company: "Drip Capital",
        location: "Mumbai",
        mode: "Remote",
        experience: "3-5",
        skills: ["Rails", "React", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "25–45 LPA",
        applyUrl: "https://www.dripcapital.com/careers",
        description: "Lead the development of trade finance solutions. Help small businesses globally access credit through our platform."
    },
    {
        id: 57,
        title: "Software Engineer",
        company: "Cisco",
        location: "Bengaluru",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["C", "Networking", "Python"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "14–22 LPA",
        applyUrl: "https://www.cisco.com/careers",
        description: "Work on the brains of the internet. Develop and maintain networking protocols for Cisco's high-speed routers."
    },
    {
        id: 58,
        title: "Product Design Intern",
        company: "Dunzo",
        location: "Bengaluru",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Figma", "Visual Design", "Wireframing"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹20k–₹35k/month Internship",
        applyUrl: "https://www.dunzo.com/careers",
        description: "Work on the app that defines hyper-local delivery in India. Help us design seamless experiences for our users and partners."
    },
    {
        id: 59,
        title: "Junior Data Scientist",
        company: "Sigmoid",
        location: "Bengaluru",
        mode: "Remote",
        experience: "0-1",
        skills: ["Sparks", "Python", "SQL"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "7–12 LPA",
        applyUrl: "https://www.sigmoid.com/careers",
        description: "Unlock the power of data for global enterprises. Build scalable data science solutions and ETL pipelines."
    },
    {
        id: 60,
        title: "Backend Developer",
        company: "Shiprocket",
        location: "Gurugram",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["PHP", "C#", "SQL Server"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "10–18 LPA",
        applyUrl: "https://www.shiprocket.in/careers",
        description: "Power the logistics for thousands of D2C brands. Optimize our shipping platform for speed, cost, and reliability."
    }
];
